modLoader="javafml"
loaderVersion="[43,)"
license="CC0-1.0"
[[mods]]
	modId="overworld_quartz_ore"
	version="${file.jarVersion}"
	displayName="Overworld Quartz Ore"
	logoFile="icon.png"
	authors="artemis"
	description="Adds quartz ore to the overworld"
[[dependencies.overworld_quartz_ore]]
	modId="forge"
	mandatory=true
	versionRange="[43,)"
	ordering="NONE"
	side="BOTH"
[[dependencies.overworld_quartz_ore]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19.2,1.19.3)"
	ordering="NONE"
	side="BOTH"
